project:
  type: website

website:
  title: "Website"
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: "Introduction"  # Changed from Home to Introduction
      - href: TerrelPenrosePage/Terrel_Penrose.qmd
        text: "Terrell-Penrose Effect" # Optional: adds a cleaner title
      - href: QEC/RepetitionCode/RepetitionCode.qmd
        text: "RepetitionCode"
      - href: QEC/UF_Decoder/UF_Decoder.qmd
        text: "Union Find Decoder"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


