---
title: "Hi, I'm Jamie"
format:
  html:
    toc: false
    theme: cosmo
---


I’m a third-year Physics (Msci) undergraduate student at the University of Bristol
You can find my projects on github at https://github.com/Jdev31 or you can find some more in depth descriptions in the other sections of the website.

## Recent Projects

### **Simulating the Terrel-Penrose Effect**
Comparing the effects of length contraction to the visual appearance of simple shapes at relativistic speeds

### **The Repetition Code: An Introduction to Quantum Error Correction**
Using Googles python library `stim` to build a classical Repetition Code error correction from scratch, and Investigating the how the logical error rate depends on code distance 

### **Building and Comparing Decoders on Surface Codes Using Stim**
Different error correction codes usually have tradeoff between scalability and accuracy. I devloped a Union Find Decoder code and compared it to Minimum Weight Perfect Matching for a surface code.

### **Building a Physics Informed Neural Network (PINN)**
Created a PINN that forecasts the position of a one dimensional simple harmonic oscillator.
Implemented a Baysian Optimisation Algorithm to optimise the hyperparameters of the model 


## Older Projects Found on Github

### **GravitySim**
A numerical simulation of the three-body problem, written in C#.  
Shows gravitational dynamics between three interacting bodies.

### **OilDropExp**
The complete Millikan oil drop experiment report from my first-year labs — with data analysis code in Python and the final formal write-up included.

### **ArtifactCode**
C# code developed as part of my Extended Project Qualification (EPQ) along with the written essay.
